### PR TITLE
Spelling corrections and some grammar changes

### PR DESCRIPTION
**Pull request by dbmalkovsky**
- Spelling corrections
- grammar changes
- update .gitignore file for IntelliJ

I can do more updates of this nature if they are useful.   I stopped where I did to get some feedback.

### CODE REVIEW

**Comment by mwithi** [comment]
Wow! Thanks a lot for you work @dbmalkovsky !!!

Indeed, I've just doing some refactoring on both User and Admin manuals, to achieve better formatting using Asciidoc. If you like you can take in charge OP-281!

About this you can go on, maybe it is better to put it in draft state until is not ready to be merged, wdyt?

**Comment by mwithi** [comment]
> I can do more updates of this nature if they are useful. I stopped where I did to get some feedback.

Hi @dbmalkovsky, is this PR finished or you had in plan to append more changes?

**Comment by dbmalkovsky** [comment]
@mwithi Sorry, I didn't see your question.   I am still working on the Admin document.   I think this one can be closed and I'll open another one attached to [OP-281](https://openhospital.atlassian.net/browse/OP-281).  I am in the home stretch of my first pass. I am currently working on section 5.2.

**Comment by dbmalkovsky** [comment]
Closing as some of these changes have been pushed and the rest I'm still working on.

**Pull request closed without merging**
