### PR TITLE
OP-89 opd next visit

### PR DESCRIPTION
**Pull request by ghost**

### CODE REVIEW

**Comment by mwithi** [comment]
This PR seems containing changes not related to OP-89 only, please verify...

**Comment by MartinezX21** [comment]
> 
> 
> This PR seems containing changes not related to OP-89 only, please verify...

Yes it also contains changes related to OP-84, OP-87, OP-88 and OP-90 concerned by this pull request: https://github.com/informatici/openhospital-doc/pull/9; that is because these tasks  were done on a branch from which the branch used for the task OP-89 was created. So I think we should merge the PR #9, rebase the PR #11 on a branch on top of the one where the PR #9 was merged before merging it.
Hope this helps.

**Comment by mwithi** [comment]
Ok, clear. Before to merge #9 there are some change requests to solve first.

**Comment by MartinezX21** [comment]
> 
> 
> Ok, clear. Before to merge #9 there are some change requests to solve first.

Yes, of course.

**Pull request merged**
