### PR TITLE
OP-507 More incremental changes

### PR DESCRIPTION
**Pull request by dbmalkovsky**

### CODE REVIEW

**Review by mizzioisf — APPROVED** [review]
Nice !
What about putting "a patient must be selected from the list" in place of "one must select..." ?
Does it make sense ?
I think we should also decide a general common setting in the documentation on how to relate to the user: there are still places where we relate to users with "you".

**Comment by dbmalkovsky** [comment]
Yes it makes sense;  I was first trying to remove the remaining 283 "you" references and adopt other standard styles.  I like your suggestion.

**Comment by mizzioisf** [comment]
good ! This PR is perfectly fine for me :-)

**Comment by dbmalkovsky** [comment]
BTW, I would love to change `progressive number` to `sequence number` as it is much more natural (at least to me).

**Comment by dbmalkovsky** [comment]
@mizzioisf is Alessandro  off an another project? I haven't seem him online for multiple days

**Comment by mizzioisf** [comment]
Yes, he will be back this week.

**Comment by dbmalkovsky** [comment]
I was waiting on the commit before I made the next round of changes so as to limit the number of conflicts.

**Comment by mizzioisf** [comment]
I agree.

**Review by mwithi — APPROVED** [review]
LGTM. Thanks a lot everybody!

**Comment by dbmalkovsky** [comment]
@miz

**Pull request merged**
