### PR TITLE
OP-507 small incremental changes to grammar, spelling, etc.

### PR DESCRIPTION
**Pull request by dbmalkovsky**
Corrected a few window titles too.

### CODE REVIEW

**Review by mizzioisf — APPROVED** [review]
Thank you David ! Nice job !
The only thing I would say is that I wouldn't put a comma before "and", at least not in italian, not sure about english :-)

**Comment by dbmalkovsky** [comment]
There is a debate about the comma before "and" in English; the traditionalists (i.e., old timers like me) tend to still use it :)

**Review by mwithi — APPROVED** [review]
LGTM. Thanks!

**Comment by mwithi** [comment]
> There is a debate about the comma before "and" in English; the traditionalists (i.e., old timers like me) tend to still use it :)

about this I prefer without the comma, but solely for a personal taste

**Pull request merged**
