### PR TITLE
Op 174 creative common license to doc

### PR DESCRIPTION
**Pull request by giuseppesorge**
Added creative Common license CC BY-SA to user and admin manual

### CODE REVIEW

**Comment by giuseppesorge** [comment]
Wrong pull request

**Comment by giuseppesorge** [comment]
Fixed branch

**Review by mwithi — COMMENTED** [review]
I saw that GitHub allows also to add a LICENSE file in the repository with some templates:
image

It doesn't seem to provide CC by-sa 4.0, but maybe we can just put in it whatever we find as text. What do you think? This in addition to the asciidoc changes.

**Comment by rospus** [comment]
> I saw that GitHub allows also to add a LICENSE file in the repository with some templates:
> image
> 
> It doesn't seem to provide CC by-sa 4.0, but maybe we can just put in it whatever we find as text. What do you think? This in addition to the asciidoc changes.

Probably because github focuses on software's code and CC on content.

**Comment by mwithi** [comment]
There is CC Zero v1 Universal, but we could also create the file LICENSE anyway and put inside any text, the problem is that I failed to find any text...

**Review by rospus — CHANGES_REQUESTED** [review]
Hi Giuseppe, thanks for your help.
About the license, I would use a integrated version due to the fact that the same contents are used both online and offline (PDF). This is what I suggest for the admin's manual, issuing machine readable meta data. Please change accordingly the title for the user's manual.
```
<a rel="license" href="http://creativecommons.org/licenses/by-sa/4.0/"><img alt="Creative Commons License" style="border-width:0" src="https://i.creativecommons.org/l/by-sa/4.0/88x31.png" /></a> Informatici Senza Frontiere Onlus, 2020<br />
<span xmlns:dct="http://purl.org/dc/terms/" property="dct:title">Administrator’s Guide</span>, &copy; 2020 by <a xmlns:cc="http://creativecommons.org/ns#" href="https://www.informaticisenzafrontiere.org/" property="cc:attributionName" rel="cc:attributionURL">Informatici Senza Frontiere Onlus</a>.<br />
Policies is made available under a <a rel="license" href="http://creativecommons.org/licenses/by-sa/4.0/">Creative Commons Attribution-ShareAlike 4.0</a> International License: http://creativecommons.org/licenses/by-sa/4.0/.
```

**Comment by giuseppesorge** [comment]
Hi, unfortunately I can't insert meta data inside the pdf created by ASCIIDOCTOR. If you want I can try to insert a static text as similar as possible to the result of metadata provided by you. Let me know if for you it is ok this workaround.

**Comment by rospus** [comment]
@Giuseppe: don't worry about the meta data, give priority to the visualization then implement the wording as it would be rendered by browsers. Thanks.

**Comment by giuseppe** [comment]
@giuseppesorge ^

**Comment by mwithi** [comment]
**EDIT**: Sorry, my mistake, now I got it 😁

@giuseppe I think you deleted @giuseppesorge 's message... that was 

> Hi, unfortunately I can't insert meta data inside the pdf created by ASCIIDOCTOR. If you want I can try to insert a static text as similar as possible to the result of metadata provided by you. Let me know if for you it is ok this workaround.

@rospus did you read that?

**Comment by giuseppesorge** [comment]
Hi, thank you very much for your suggestion @rospus. As of now I'm facing with the problem 'could not embed image' due to this issue https://github.com/asciidoctor/asciidoctor-pdf/issues/545. And also I have another problem with the parse of metadata suggested by you.
Let me check the documentation to understand the better way to solve the problem.

**Comment by giuseppesorge** [comment]
Below there are the new page 3 and the new page 56 of Administrator's manual.  @rospus let me know if it is ok for you. I tried to replicate the same result rendered by your html.

**Page 3**
image

**Pag 56**
image

**Comment by rospus** [comment]
Good job, Giuseppe.

**Review by rospus — APPROVED** [review]
@mwithi: ok to merge.

**Review by rospus — APPROVED** [review]
@mwithi: ok to merge

**Pull request merged**
